pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
              	sh 'javac -encoding UTF-8 -d classes -cp /Users/gang-yunho/eclipse/plugins/junit-platform-console-standalone-1.7.1.jar SoftWareClass/src/*.java'
            }
        }
        stage('Test') {
            steps {
                script {
    				def classpath = "classes:/Users/gang-yunho/eclipse/plugins/junit-platform-console-standalone-1.7.1.jar"
    				sh "java -cp ${classpath} org.junit.platform.console.ConsoleLauncher --scan-classpath > test_results.txt"
				}
            }
        }
        stage('Run PerformanceTest') {
            steps {
                script {
                    def classpath = "classes"
                    sh "java -cp ${classpath} PerformanceTest > performance_results.txt"
                }
            }
        }
        stage('Commit and Push Results') {
            steps {
                script {
                    sh '''
                    git config user.name "Wide-Pants"
                    git config user.email "ajtwoddl1236@naver.com"
                    git add test_results.txt performance_results.txt
                    git commit -m "Add build and test results"
                    git push https://Wide-Pants@https://github.com/Wide-Pants/SoftwareClass.git HEAD:master
                    '''
                }
            }
        }
    }
    
    post {
        always {
            archiveArtifacts artifacts: 'test_results.txt'
            archiveArtifacts artifacts: 'performance_results.txt'
        }
        failure {
            echo 'Build or test failed'
        }
        success {
            echo 'Build and test succeeded'
        }
    }
}
