pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
              	sh 'javac -encoding UTF-8 -d classes SoftWareClass/src/BookList.java'
            }
        }
        stage('Test') {
            steps {
                script {
    				def classpath = "classes:lib/:path/to/eclipse/plugins/junit-platform-console-standalone-1.7.1.jar"
    				sh "java -cp ${classpath} org.junit.platform.console.ConsoleLauncher --scan-classpath > test_results.txt 2>&1"
				}
            }
        }
    }
    
    post {
        always {
            archiveArtifacts artifacts: 'build_results.txt'
            archiveArtifacts artifacts: 'test_results.txt'
        }
        failure {
            echo 'Build or test failed'
        }
        success {
            echo 'Build and test succeeded'
        }
    }
}
